// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GFTfjSSi0JqzXCsVqtWHzpZaQxOs4ro',
    appId: '1:204404478676:web:f5213fd9eec17a58ade141',
    messagingSenderId: '204404478676',
    projectId: 'fleet-pulse',
    authDomain: 'fleet-pulse.firebaseapp.com',
    storageBucket: 'fleet-pulse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQ2x2bGF0J_v3804wzs5R4rM_os8hDWM',
    appId: '1:204404478676:android:c2eaa18bd2d66885ade141',
    messagingSenderId: '204404478676',
    projectId: 'fleet-pulse',
    storageBucket: 'fleet-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGzVEPWFv2fpSRsIQiZurkfNh39kv84o',
    appId: '1:204404478676:ios:47706e60d1164558ade141',
    messagingSenderId: '204404478676',
    projectId: 'fleet-pulse',
    storageBucket: 'fleet-pulse.firebasestorage.app',
    iosBundleId: 'com.example.fleetPulse',
  );
}